src/App/MainBundle/Entity/TestFolder.php
<?php

namespace App\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use JsonSerializable;

/**
 * @ORM\Entity
 * @ORM\Table(name="test_folder", uniqueConstraints={
 *      @ORM\UniqueConstraint(name="IDX_Unique_Application", columns={"name", "application_id"}),
 *      @ORM\UniqueConstraint(name="IDX_Unique_Test_Folder", columns={"name", "parent_id"})
 * })
 * @UniqueEntity(
 *      fields={"name", "application"},
 *      message="Name already used.",
 *      groups="test_folder_application"
 * )
 * @UniqueEntity(
 *      fields={"name", "testFolder"},
 *      message="Name already used.",
 *      groups="test_folder_test_folder"
 * )
 */
class TestFolder implements JsonSerializable {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(
     *      message = "Name cannot be empty."
     * )
     * @Assert\Length(
     *      min = "3",
     *      max = "50",
     *      minMessage = "Name is too short. It should have {{ limit }} characters or more.",
     *      maxMessage = "Name is too long. It should have {{ limit }} characters or less."
     * )
     */
    protected $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description = "";

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;
    protected $selected = false;

    /**
     * @ORM\ManyToOne(targetEntity="Application", inversedBy="testFolders")
     * @ORM\JoinColumn(name="application_id", referencedColumnName="id")
     */
    protected $application;

    /**
     * @ORM\ManyToOne(targetEntity="TestFolder", inversedBy="testFolders")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true)
     */
    protected $testFolder;

    /**
     * @ORM\OneToMany(targetEntity="TestFolder", mappedBy="testFolder", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $testFolders;

    /**
     * @ORM\OneToMany(targetEntity="Test", mappedBy="testFolder", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $tests;

    public function __construct() {
        $this->createdAt = new \DateTime();
        $this->testFolders = new ArrayCollection();
        $this->tests = new ArrayCollection();
    }

    public function __toString() {
        $result = "";
        if ($this->testFolder != null) {
            $result .= $this->testFolder . "\\";
        }
        if ($this->name != null && $this->name != "") {
            $result .= $this->name;
            return $result;
        }
        return "New";
    }

    public function jsonSerialize() {
        return array(
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'createdAt' => $this->createdAt->format('d/m/Y \a\t H:i:s'),
            'application' => $this->application
        );
    }

    public function getTestFoldersCount() {
        $count = $this->testFolders->count();
        foreach ($this->testFolders as $testFolder) {
            $count += $testFolder->getTestFoldersCount();
        }
        return $count;
    }

    public function getTestsCount() {
        $count = $this->getTests()->count();
        foreach ($this->testFolders as $testFolder) {
            $count += $testFolder->getTestsCount();
        }
        return $count;
    }

    public function getJsonTreeAsArray() {
        $result = array(
            'text' => $this->name . ' <span class="pull-right"><small>' . $this->description . '</small></span>',
            'icon' => 'fontello-icon-folder',
            'href' => '#node-folder-' . $this->id,
            'state' => array(
                'selected' => $this->selected
        ));
        if ($this->testFolders->count() > 0 || $this->tests->count() > 0) {
            $result["nodes"] = $this->getNodes();
        }
        return $result;
    }

    private function getNodes() {
        $nodes = array();
        foreach ($this->testFolders as $testFolder) {
            $nodes[] = $testFolder->getJsonTreeAsArray();
        }
        foreach ($this->tests as $test) {
            $nodes[] = $test->getJsonTreeAsArray();
        }
        return $nodes;
    }

    public function getRootApplication() {
        $application = $this->application;
        $parent = $this->testFolder;
        while ($application == null && $parent != null) {
            $application = $parent->getApplication();
            $parent = $parent->getTestFolder();
        }
        return $application;
    }

    public function getParentName() {
        if ($this->testFolder === null) {
            return $this->name;
        }
        return $this->testFolder->getParentName() . " > " . $this->name;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return TestFolder
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return TestFolder
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return TestFolder
     */
    public function setCreatedAt($createdAt) {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt() {
        return $this->createdAt;
    }

    function getSelected() {
        return $this->selected;
    }

    function setSelected($selected) {
        $this->selected = $selected;
    }

    /**
     * Set application
     *
     * @param \App\MainBundle\Entity\Application $application
     * @return TestFolder
     */
    public function setApplication(\App\MainBundle\Entity\Application $application = null) {
        $this->application = $application;

        return $this;
    }

    /**
     * Get application
     *
     * @return \App\MainBundle\Entity\Application
     */
    public function getApplication() {
        return $this->application;
    }

    /**
     * Set testFolder
     *
     * @param \App\MainBundle\Entity\TestFolder $testFolder
     * @return TestFolder
     */
    public function setTestFolder(\App\MainBundle\Entity\TestFolder $testFolder = null) {
        $this->testFolder = $testFolder;

        return $this;
    }

    /**
     * Get testFolder
     *
     * @return \App\MainBundle\Entity\TestFolder
     */
    public function getTestFolder() {
        return $this->testFolder;
    }

    /**
     * Add testFolders
     *
     * @param \App\MainBundle\Entity\TestFolder $testFolders
     * @return TestFolder
     */
    public function addTestFolder(\App\MainBundle\Entity\TestFolder $testFolders) {
        $testFolders->testFolder = $this;
        $this->testFolders[] = $testFolders;

        return $this;
    }

    /**
     * Remove testFolders
     *
     * @param \App\MainBundle\Entity\TestFolder $testFolders
     */
    public function removeTestFolder(\App\MainBundle\Entity\TestFolder $testFolders) {
        $this->testFolders->removeElement($testFolders);
    }

    /**
     * Get testFolders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTestFolders() {
        return $this->testFolders;
    }

    /**
     * Add tests
     *
     * @param \App\MainBundle\Entity\Test $tests
     * @return TestFolder
     */
    public function addTest(\App\MainBundle\Entity\Test $tests) {
        $tests->setTestFolder($this);
        $tests->setApplication($this->getRootApplication());
        $this->tests[] = $tests;

        return $this;
    }

    /**
     * Remove tests
     *
     * @param \App\MainBundle\Entity\Test $tests
     */
    public function removeTest(\App\MainBundle\Entity\Test $tests) {
        $this->tests->removeElement($tests);
    }

    /**
     * Get tests
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTests() {
        return $this->tests;
    }

}

src/App/MainBundle/Form/Type/TestSetType.php
<?php

namespace App\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class TestSetType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('name', 'text', array(
            'icon' => 'pencil'
        ));
        $builder->add('description', 'textarea', array(
            'required' => false,
            'icon' => 'info'
        ));
    }

    public function getName() {
        return 'test_set';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'App\MainBundle\Entity\TestSet',
            'validation_groups' => array('Default', 'test_set'),
            'cascade_validation' => true
        ));
    }

}

src/App/MainBundle/Resources/views/test-set/editor/behat.html.twig
<div class="row test-set-behat">
    <div class="col-md-12">
        <h3 class="text-center">
            <strong>
                <i class="fontello-icon-gauge"></i> Behat
            </strong>
        </h3>
    </div>
    <div class="well col-md-8 col-md-offset-2">
        <samp id="behat-feature">
            {% include "AppMainBundle:test-set:editor/behat_content.html.twig" %}
        </samp>
    </div>
</div>

src/App/MainBundle/Resources/views/test-set/editor/behat_content.html.twig
{{ testSet.behatFeature(gherkin)|raw|nl2br }}

src/App/MainBundle/Resources/views/test-set/editor/execution-grid.html.twig
<div class="row test-set-execution-grid">
    <div class="col-md-12">
        <h3 class="text-center">
            <span class="pull-left">
                <a href="#execution-grid-collapse" data-toggle="collapse" aria-expanded="false" aria-controls="execution-grid-collapse">
                    <i class="fontello-icon-up-open execution-grid-collapse-toggle-icon"></i></a>
            </span>
            <strong>
                <i class="fontello-icon-table"></i> Execution Grid
                <a href="#" id="refresh-execution-grid" data-toggle="tooltip"
                   title="Refresh"
                   data-placement="right"
                   data-id="{{ testSet.id }}"><i class="fontello-icon-arrows-cw"></i></a>
            </strong>
            <span class="pull-right">
                <a href="#execution-grid-collapse" data-toggle="collapse" aria-expanded="false" aria-controls="execution-grid-collapse">
                    <i class="fontello-icon-up-open execution-grid-collapse-toggle-icon"></i></a>
            </span>
        </h3>
    </div>
</div>
<div class="collapse in" id="execution-grid-collapse">
    <div class="row">
        {% include "AppMainBundle:test-set:editor/execution-grid_content.html.twig" %}
    </div>
    {% include 'AppMainBundle:test-set:editor/run.html.twig' %}
</div>

src/App/MainBundle/Resources/views/test-set/editor/execution-grid_content.html.twig
<div id="execution-grid">
    {% include "AppMainBundle:test-set:editor/execution-grid_table.html.twig" with { 'showActions': true } %}
    <p class="text-center">
        <span id="test-instances-count-{{ testSet.id }}">
            {% if testSet.testInstances|length <= 1 %}There is {% else %}There are{% endif %}
            {% if testSet.testInstances|length == 0 %}no {% else %}<span class="badge">{{ testSet.testInstances|length }}</span>{% endif %}
            scenario instance{% if testSet.testInstances|length > 1 %}s{% endif %} in the execution grid
        </span>
    </p>
    <p class="text-center">
        <a href="#" id="add-test-instance"
           class="btn btn-xs btn-custom-purple"
           data-toggle="tooltip" data-placement="right" title="Add a new scenario instance">
           New <i class="fontello-icon-tint"></i>
        </a>
    </p>
</div>

src/App/MainBundle/Resources/views/test-set/editor/execution-grid_table.html.twig
<table id="execution-grid-{{ testSet.id }}"
        class="table table-hover table-condensed table-striped table-responsive table-bordered">
    <thead>
        <tr>
            <th class="text-center"><i class="fontello-icon-sort"></i>Order</th>
            <th class="text-center"><i class="fontello-icon-ellipsis-vert"></i>Scenario</th>
            <th class="text-center"><i class="fontello-icon-flag-checkered"></i>Last Status</th>
            <th class="text-center"><i class="fontello-icon-upload-cloud"></i>Last Requested</th>
            <th class="text-center"><i class="fontello-icon-cloud"></i>Last Execution Server</th>
            {% if showActions %}
                <th class="text-center"><i class="fontello-icon-edit"></i>Actions</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for testInstance in testSet.testInstances %}
            {% include "AppMainBundle:test:instance/item.html.twig" with { 
                'testInstance': testInstance,
                'position': loop.index,
                'showActions': showActions
            } %}
        {% endfor %}
    </tbody>
</table>

src/App/MainBundle/Resources/views/test-set/editor/index.html.twig
{% extends 'base.html.twig' %}
{% set page_ = "test-set-editor" %}
{% set context = "custom-purple" %}

{% block jumbotronTitle %}
    <span class="text-{{ context }}">
        <i class="fontello-icon-beaker"></i><strong>Feature</strong> Editor
    </span>
{% endblock %}

{% set application = testSet.testSetFolder.rootApplication %}

{% block jumbotronBody %}
    <p class="text-center">
        <a href="{{ path('app_index_application_test_set_planner', { 'id': application.id }) }}">
            <i class="fontello-icon-left-circled"></i>Return to <strong>{{ application.name }}</strong> Feature Lab
        </a>
    </p>
{% endblock %}

{% block breadcrumb_items %}
    <li>
        <a href="{{ path('homepage') }}"><i class="fontello-icon-right-open"></i>Home</a>
    </li>
    <li>
        <a href="{{ path('app_index_project', { 'id': application.project.id }) }}">
            <i class="fontello-icon-right-open"></i>{{ application.project }}</a>
    </li>
    <li>
        <a href="{{ path('app_index_application', { 'id': application.id }) }}">
            <i class="fontello-icon-right-open"></i>{{ application }}</a>
    </li>
    <li>
        <a href="{{ path('app_index_application_test_set_planner', { 'id': application.id }) }}">
            <i class="fontello-icon-right-open"></i>Feature Lab</a>
    </li>
    <li class="active">
        <i class="fontello-icon-angle-circled-right"></i>{{ testSet }}
    </li>
{% endblock %}

{% block body %}
    {% include 'AppMainBundle:test-set:editor/execution-grid.html.twig' %}
    {# include 'AppMainBundle:test-set:editor/behat.html.twig' #}
{% endblock %}

{% block modals %}
    {% include 'AppMainBundle:test:instance/new.form.html.twig' %}
    {% include 'AppMainBundle:test:instance/details.html.twig' %}
    {% include 'AppMainBundle:test-set:run/new.form.html.twig' %}
    {% include 'AppMainBundle:test-set:run/history.html.twig' %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function() {
            TestSetEditor.init();
            TestSetEditor.initItem({{ testSet.id }});
            TestInstanceManager.init();
            TestPlanner.refresh({{ application.id }}, true, true);
        });
    </script>
{% endblock %}

src/App/MainBundle/Resources/views/test-set/editor/run.html.twig
<div class="row">
    <p class="text-center">
        <a href="#" class="btn btn-lg btn-success" id="run-test-set" data-id="{{ testSet.id }}">
            <i class="fontello-icon-play"></i>Run
        </a>
        <a href="#" class="btn btn-lg btn-info" id="show-test-set-history" data-id="{{ testSet.id }}">
            <i class="fontello-icon-back-in-time"></i>Show history
        </a>
    </p>
</div>