src/App/MainBundle/Entity/Application.php
<?php

namespace App\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use JsonSerializable;

/**
 * @ORM\Entity
 * @ORM\Table(name="application", uniqueConstraints={@ORM\UniqueConstraint(name="IDX_Unique", columns={"name", "project_id"})})
 * @UniqueEntity(
 *      fields={"name", "project"},
 *      message="Name already used in this project.",
 *      groups="application"
 * )
 */
class Application implements JsonSerializable {

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(
     *      message = "Name cannot be empty."
     * )
     * @Assert\Length(
     *      min = "3",
     *      max = "50",
     *      minMessage = "Name is too short. It should have {{ limit }} characters or more.",
     *      maxMessage = "Name is too long. It should have {{ limit }} characters or less."
     * )
     */
    protected $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description = "";

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Assert\Url()
     */
    protected $url;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="ObjectMap", mappedBy="application", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    protected $objectMaps;

    /**
     * @ORM\OneToMany(targetEntity="TestFolder", mappedBy="application", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $testFolders;

    /**
     * @ORM\OneToMany(targetEntity="BusinessStepFolder", mappedBy="application", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $businessStepFolders;

    /**
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="applications")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id")
     */
    protected $project;

    /**
     * @ORM\OneToMany(targetEntity="TestSetFolder", mappedBy="application", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"name" = "ASC"})
     */
    protected $testSetFolders;

    public function __construct() {
        $this->createdAt = new \DateTime();
        $this->objectMaps = new ArrayCollection();
        $this->testFolders = new ArrayCollection();
        $this->testSetFolders = new ArrayCollection();
        $this->businessStepFolders = new ArrayCollection();
    }

    public function __toString() {
        if ($this->name != null && $this->name != "") {
            return $this->name;
        }
        return "New";
    }

    public function jsonSerialize() {
        return array(
            'id' => $this->id,
            'name' => $this->name,
            'description' => $this->description,
            'createdAt' => $this->createdAt->format('d/m/Y H:i:s'),
            'url' => $this->url,
            'project' => $this->project
        );
    }

    public function getPagesCount() {
        $result = 0;
        foreach ($this->objectMaps as $objectMap) {
            $result += $objectMap->getPagesCount();
        }
        return $result;
    }

    public function getObjectsCount() {
        $result = 0;
        foreach ($this->objectMaps as $objectMap) {
            $result += $objectMap->getObjectsCount();
        }
        return $result;
    }

    public function getTestFoldersCount() {
        $count = $this->testFolders->count();
        foreach ($this->testFolders as $testFolder) {
            $count += $testFolder->getTestFoldersCount();
        }
        return $count;
    }

    public function getTestsCount() {
        $count = 0;
        foreach ($this->testFolders as $testFolder) {
            $count += $testFolder->getTestsCount();
        }
        return $count;
    }

    public function getJsonTestsTreeAsArray() {
        $result = array();
        foreach ($this->testFolders as $testFolder) {
            $result[] = $testFolder->getJsonTreeAsArray();
        }
        return $result;
    }

    public function getTestSetFoldersCount() {
        $count = $this->testSetFolders->count();
        foreach ($this->testSetFolders as $testSetFolder) {
            $count += $testSetFolder->getTestSetFoldersCount();
        }
        return $count;
    }

    public function getTestSetsCount() {
        $count = 0;
        foreach ($this->testSetFolders as $testSetFolder) {
            $count += $testSetFolder->getTestSetsCount();
        }
        return $count;
    }

    public function getJsonTestSetsTreeAsArray() {
        $result = array();
        foreach ($this->testSetFolders as $testSetFolder) {
            $result[] = $testSetFolder->getJsonTreeAsArray();
        }
        return $result;
    }

    public function getBusinessStepFoldersCount() {
        $count = $this->businessStepFolders->count();
        foreach ($this->businessStepFolders as $businessStepFolder) {
            $count += $businessStepFolder->getBusinessStepFoldersCount();
        }
        return $count;
    }

    public function getBusinessStepsCount() {
        $count = 0;
        foreach ($this->businessStepFolders as $businessStepFolder) {
            $count += $businessStepFolder->getBusinessStepsCount();
        }
        return $count;
    }

    public function getJsonBusinessStepsTreeAsArray() {
        $result = array();
        foreach ($this->businessStepFolders as $businessStepFolder) {
            $result[] = $businessStepFolder->getJsonTreeAsArray();
        }
        return $result;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Application
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Application
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Application
     */
    public function setCreatedAt($createdAt) {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt() {
        return $this->createdAt;
    }

    /**
     * Set project
     *
     * @param \App\MainBundle\Entity\Project $project
     * @return Application
     */
    public function setProject(\App\MainBundle\Entity\Project $project = null) {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return \App\MainBundle\Entity\Project
     */
    public function getProject() {
        return $this->project;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Application
     */
    public function setUrl($url) {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl() {
        return $this->url;
    }

    /**
     * Add objectMaps
     *
     * @param \App\MainBundle\Entity\ObjectMap $objectMaps
     * @return Application
     */
    public function addObjectMap(\App\MainBundle\Entity\ObjectMap $objectMaps) {
        $objectMaps->setApplication($this);
        $this->objectMaps[] = $objectMaps;

        return $this;
    }

    /**
     * Remove objectMaps
     *
     * @param \App\MainBundle\Entity\ObjectMap $objectMaps
     */
    public function removeObjectMap(\App\MainBundle\Entity\ObjectMap $objectMaps) {
        $this->objectMaps->removeElement($objectMaps);
    }

    /**
     * Get objectMaps
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getObjectMaps() {
        return $this->objectMaps;
    }

    /**
     * Add testFolders
     *
     * @param \App\MainBundle\Entity\TestFolder $testFolders
     * @return Application
     */
    public function addTestFolder(\App\MainBundle\Entity\TestFolder $testFolders) {
        $testFolders->setApplication($this);
        $this->testFolders[] = $testFolders;

        return $this;
    }

    /**
     * Remove testFolders
     *
     * @param \App\MainBundle\Entity\TestFolder $testFolders
     */
    public function removeTestFolder(\App\MainBundle\Entity\TestFolder $testFolders) {
        $this->testFolders->removeElement($testFolders);
    }

    /**
     * Get testFolders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTestFolders() {
        return $this->testFolders;
    }

    /**
     * Add testSetFolders
     *
     * @param \App\MainBundle\Entity\TestSetFolder $testSetFolders
     * @return Application
     */
    public function addTestSetFolder(\App\MainBundle\Entity\TestSetFolder $testSetFolders) {
        $testSetFolders->setApplication($this);
        $this->testSetFolders[] = $testSetFolders;

        return $this;
    }

    /**
     * Remove testSetFolders
     *
     * @param \App\MainBundle\Entity\TestSetFolder $testSetFolders
     */
    public function removeTestSetFolder(\App\MainBundle\Entity\TestSetFolder $testSetFolders) {
        $this->testSetFolders->removeElement($testSetFolders);
    }

    /**
     * Get testSetFolders
     *

src/App/MainBundle/Form/Type/ApplicationType.php
<?php

namespace App\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ApplicationType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder->add('name', 'text', array(
            'icon' => 'pencil'
        ));
        $builder->add('description', 'textarea', array(
            'required' => false,
            'icon' => 'info'
        ));
        $builder->add('url', 'url', array(
            'required' => false,
            'icon' => 'link'
        ));
    }

    public function getName() {
        return 'application';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'App\MainBundle\Entity\Application',
            'validation_groups' => array('Default', 'application'),
            'cascade_validation' => true
        ));
    }

}

src/App/MainBundle/Controller/ApplicationController.php
<?php

namespace App\MainBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\MainBundle\Entity\Application;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ApplicationController extends BaseController {

    /**
     * @Route("/application/{id}", name="app_index_application")
     * @Secure(roles="ROLE_USER")
     * @ParamConverter("application", class="AppMainBundle:Application")
     */
    public function indexAction(Application $application) {
        return $this->render('AppMainBundle:application:index.html.twig', array(
                    'application' => $application
        ));
    }

    /**
     * @Route("/application/{id}/update/name",
     *      name="app_application_update_name_ajax",
     *      requirements={"_method" = "post"},
     *      options={"expose" = true }
     * )
     * @Secure(roles="ROLE_USER")
     */
    public function updateNameAction(Request $request) {
        if ($request->getMethod() == 'POST' && $request->isXmlHttpRequest()) {
            $em = $this->getDoctrine()->getManager();
            $application = $em->getRepository('AppMainBundle:Application')->find($request->get("pk"));
            if ($application != null) {
                $application->setName($request->get("value"));
                $validator = $this->get('validator');
                $errors = $validator->validate($application);
                if (count($errors) == 0) {
                    $em->persist($application);
                    $em->flush();
                    $name = "" . $application;
                    $response = new Response(json_encode($name));
                } else {
                    $message = "";
                    foreach ($errors as $err) {
                        if ($message !== "") {
                            $message .= "\n";
                        }
                        $message .= $err->getMessage();
                    }
                    $response = new Response($message, 400);
                }
            } else {
                $response = new Response("Unknown project", 400);
            }
        }
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/application/{id}/update/description",
     *      name="app_application_update_description_ajax",
     *      requirements={"_method" = "post"},
     *      options={"expose" = true }
     * )
     * @Secure(roles="ROLE_USER")
     */
    public function updateDescriptionAction(Request $request) {
        if ($request->getMethod() == 'POST' && $request->isXmlHttpRequest()) {
            $em = $this->getDoctrine()->getManager();
            $application = $em->getRepository('AppMainBundle:Application')->find($request->get("pk"));
            if ($application != null) {
                $application->setDescription($request->get("value"));
                $validator = $this->get('validator');
                $errors = $validator->validate($application);
                if (count($errors) == 0) {
                    $em->persist($application);
                    $em->flush();
                    $response = new Response(json_encode($application->getDescription()));
                } else {
                    $message = "";
                    foreach ($errors as $err) {
                        if ($message !== "") {
                            $message .= "\n";
                        }
                        $message .= $err->getMessage();
                    }
                    $response = new Response($message, 400);
                }
            } else {
                $response = new Response("Unknown project", 400);
            }
        }
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

    /**
     * @Route("/application/{id}/update/url",
     *      name="app_application_update_url_ajax",
     *      requirements={"_method" = "post"},
     *      options={"expose" = true }
     * )
     * @Secure(roles="ROLE_USER")
     */
    public function updateUrlAction(Request $request) {
        if ($request->getMethod() == 'POST' && $request->isXmlHttpRequest()) {
            $em = $this->getDoctrine()->getManager();
            $application = $em->getRepository('AppMainBundle:Application')->find($request->get("pk"));
            if ($application != null) {
                $application->setUrl($request->get("value"));
                $validator = $this->get('validator');
                $errors = $validator->validate($application);
                if (count($errors) == 0) {
                    $em->persist($application);
                    $em->flush();
                    $response = new Response(json_encode($application->getUrl()));
                } else {
                    $message = "";
                    foreach ($errors as $err) {
                        if ($message !== "") {
                            $message .= "\n";
                        }
                        $message .= $err->getMessage();
                    }
                    $response = new Response($message, 400);
                }
            } else {
                $response = new Response("Unknown project", 400);
            }
        }
        $response->headers->set('Content-Type', 'application/json');
        return $response;
    }

}

src/App/MainBundle/Resources/views/application/index.html.twig
{% extends 'base.html.twig' %}
{% set page_ = "application-manager" %}
{% set context = "custom-green" %}

{% block jumbotronTitle %}
    <span class="text-{{ context }}">
        <i class="fontello-icon-leaf"></i><strong>Application</strong> Manager
    </span>
{% endblock %}

{% block jumbotronBody %}
    <p class="text-center">
        <a href="{{ path('app_index_project', { 'id': application.project.id }) }}">
            <i class="fontello-icon-left-circled"></i>Return to <strong>{{ application.project }}</strong> project
        </a>
    </p>
{% endblock %}

{% block breadcrumb_items %}
    <li>
        <a href="{{ path('homepage') }}"><i class="fontello-icon-right-open"></i>Home</a>
    </li>
    <li>
        <a href="{{ path('app_index_project', { 'id': application.project.id }) }}">
            <i class="fontello-icon-right-open"></i>{{ application.project }}</a>
    </li>
    <li class="active">
        <i class="fontello-icon-angle-circled-right"></i><span id="breadcrumb-active-item">{{ application }}</span>
    </li>
{% endblock %}

{% block body %}
    <div class="col-md-7">
        <div class="panel panel-{{ context }}" id="panel-application-{{ application.id }}">
            <div class="panel-heading">
                <strong>
                    <i class="fontello-icon-leaf"></i>
                    <a href="#" id="name"
                       data-type="text"
                       data-pk="{{ application.id }}"
                       data-url="{{ path('app_application_update_name_ajax', { 'id': application.id }) }}"
                       data-title="Update name">{{ application.name }}</a>
                </strong>
            </div>
            <div class="panel-body" id="panel-body-{{ application.id }}">
                <blockquote>
                    <p>
                        <small>
                            <a href="#" id="description"
                               data-type="textarea"
                               data-pk="{{ application.id }}"
                               data-url="{{ path('app_application_update_description_ajax', { 'id': application.id }) }}"
                               data-title="Update description">{{ application.description }}</a>
                        </small>
                    </p>
                </blockquote>
                <p>
                    <i class="fontello-icon-link"></i> Accessible via
                    <a href="#" id="url"
                       data-type="text"
                       data-pk="{{ application.id }}"
                       data-url="{{ path('app_application_update_url_ajax', { 'id': application.id }) }}"
                       data-title="Update URL">{{ application.url }}</a>
                       <a id="goto-application-link" href="{{ application.url }}" target="about:blank"
                          {% if not application.url %}style="display: none;"{% endif %}>
                           <i class="fontello-icon-link-ext-alt"></i>
                       </a>
                </p>
            </div>
            <div class="panel-footer text-right">
                <i class="fontello-icon-calendar"></i> Created {{ application.createdAt|ago }}
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <div class="list-group">
            <a href="{{ path('app_index_application_object_map', { 'id': application.id }) }}"
               class="list-group-item list-group-item-custom-yellow">
                <h4 class="list-group-item-heading"><i class="fontello-icon-sitemap"></i> <strong>Object Map</strong> Manager</h4>
                <p class="list-group-item-text">
                    <p>Map the objects of your application</p>
                    <ul class="list-unstyled text-right">
                        <li>
                            {% if application.objectMaps|length <= 1 %}There is {% else %}There are{% endif %}
                            {% if application.objectMaps|length == 0 %}no {% else %}<span class="badge">{{ application.objectMaps|length }}</span>{% endif %}
                            object map{% if application.objectMaps|length > 1 %}s{% endif %}
                        </li>
                        {% if application.objectMaps|length > 0 %}
                            <li>
                                containing
                                <span class="badge">{{ application.pagesCount }}</span>
                                page{% if application.pagesCount > 1 %}s{% endif %}
                                and
                                <span class="badge">{{ application.objectsCount }}</span>
                                object{% if application.objectsCount > 1 %}s{% endif %}
                            </li>
                        {% endif %}
                    </ul>
                </p>
            </a>
            <a href="{{ path('app_index_application_business_step_planner', { 'id': application.id }) }}"
               class="list-group-item list-group-item-custom-brown">
                <h4 class="list-group-item-heading"><i class="fontello-icon-level-up"></i> <strong>Business Step</strong> Manager</h4>
                <p class="list-group-item-text">
                    <p>Design business steps for your scenarios</p>
                    <ul class="list-unstyled text-right">
                        <li>
                            {% if application.businessStepFoldersCount <= 1 %}There is {% else %}There are{% endif %}
                            {% if application.businessStepFoldersCount == 0 %}no {% else %}<span class="badge">{{ application.businessStepFoldersCount }}</span>{% endif %}
                            folder{% if application.businessStepFoldersCount > 1 %}s{% endif %}
                        </li>
                        {% if application.businessStepFoldersCount > 0 %}
                            <li>
                                containing <span class="badge">{{ application.businessStepsCount }}</span>
                                business step{% if application.businessStepsCount > 1 %}s{% endif %}
                            </li>
                        {% endif %}
                    </ul>
                </p>
            </a>
            <a href="{{ path('app_index_application_test_planner', { 'id': application.id }) }}"
               class="list-group-item list-group-item-custom-red">
                <h4 class="list-group-item-heading"><i class="fontello-icon-tasks"></i> <strong>Scenario</strong> Plan</h4>
                <p class="list-group-item-text">
                    <p>Describe and organize your scenarios</p>
                    <ul class="list-unstyled text-right">
                        <li>
                            {% if application.testFoldersCount <= 1 %}There is {% else %}There are{% endif %}
                            {% if application.testFoldersCount == 0 %}no {% else %}<span class="badge">{{ application.testFoldersCount }}</span>{% endif %}
                            folder{% if application.testFoldersCount > 1 %}s{% endif %}
                        </li>
                        {% if application.testFoldersCount > 0 %}
                            <li>
                                containing <span class="badge">{{ application.testsCount }}</span>
                                scenario{% if application.testsCount > 1 %}s{% endif %}
                            </li>
                        {% endif %}
                    </ul>
                </p>
            </a>
            <a href="{{ path('app_index_application_test_set_planner', { 'id': application.id }) }}"
               class="list-group-item list-group-item-custom-purple">
                <h4 class="list-group-item-heading"><i class="fontello-icon-beaker"></i> <strong>Feature</strong> Lab</h4>
                <p class="list-group-item-text">
                    <p>Define and run your features</p>
                    <ul class="list-unstyled text-right">
                        <li>
                            {% if application.testSetFoldersCount <= 1 %}There is {% else %}There are{% endif %}
                            {% if application.testSetFoldersCount == 0 %}no {% else %}<span class="badge">{{ application.testSetFoldersCount }}</span>{% endif %}
                            folder{% if application.testSetFoldersCount > 1 %}s{% endif %}
                        </li>
                        {% if application.testSetFoldersCount > 0 %}
                            <li>
                                containing <span class="badge">{{ application.testSetsCount }}</span>
                                feature{% if application.testSetsCount > 1 %}s{% endif %}
                            </li>
                        {% endif %}
                    </ul>
                </p>
            </a>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(document).ready(function() {
            ApplicationManager.initEditableData();
        });
    </script>
{% endblock %}

src/App/MainBundle/Resources/views/application/item.html.twig
<tr id="row-application-{{ application.id }}">
    <td id="cell-application-{{ application.id }}-name">
        <a href="{{ path('app_index_application', { 'id': application.id }) }}">{{ application.name }}</a>
    </td>
    <td id="cell-application-{{ application.id }}-description">{{ application.description }}</td>
    <td id="cell-application-{{ application.id }}-delete-anchor" class="text-center">
        <a href="#" id="delete-application-{{ application.id }}" data-id="{{ application.id }}"
           class="text-danger"
           data-name="{{ application.name }}" 
           data-project-id="{{ project.id }}"
           data-project-name="{{ project.name }}"
           data-toggle="tooltip" data-placement="left" title="Delete">
            <i class="fontello-icon-trash"></i></a>
    </td>
</tr>

src/App/MainBundle/Resources/views/application/list.html.twig
<table id="applications-{{ project.id }}"
        class="table table-hover table-condensed table-striped table-responsive"
        {% if project.applications|length == 0 %}style="display: none;"{% endif %}>
    <thead>
        <tr>
            <th><i class="fontello-icon-pencil"></i>Name</th>
            <th><i class="fontello-icon-info"></i>Description</th>
            <th class="text-center"><i class="fontello-icon-edit"></i>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for application in project.applications %}
            {% include "AppMainBundle:application:item.html.twig" with { 'application' : application } %}
        {% endfor %}
    </tbody>
</table>

src/App/MainBundle/Resources/views/application/new.form.html.twig
{% set form = addApplicationFormView %}
<div class="modal fade" id="modal-add-application">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-{{ context }}">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-{{ context }}">
                    <i class="fontello-icon-leaf"></i> Add an application to 
                    <strong><span id="new-application-project-name"></span></strong>
                    <small><span id="new-application-project-description"></span></small>
                </h4>
            </div>
            <div class="modal-body">
                <form id="form-add-application" name="application" method="post" action="#">
                {{ form_widget(form) }}
                {{ form_end(form) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-custom-green"
                        id="save-application"
                        data-project-id=""
                        data-project-name="">Save changes</button>
            </div>
        </div>
    </div>
</div>